apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IubWt2ZS5ydSI6IHsKCQkJImF1dGgiOiAiY205aWIzUWtkbUYxYkhRdGRHVnpkQ3R5YjJKdmREcGlOVkI2VEc5T1RXTjNVamwwV1doTldVNXNUV0ZHVERWdlNIRkdVSEZ3VHc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson